language: go
go:
- 1.14.x
os:
- linux
dist: xenial
git:
  depth: false
  quiet: true
addons:
  sonarcloud:
    organization: "spi1y"
    token:
      secure: "*********"
script:
  - make linter || true
  - make