language: go
go:
- 1.14.x
os:
- linux
dist: xenial
git:
  depth: false
  quiet: true
addons:
  sonarcloud:
    organization: "spi1y"

script:
  - make linter || true
  - make test
  - ls output/linter.xml
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'