language: go
go:
- 1.14.x
os:
- linux
dist: xenial
git:
  depth: false
  quiet: true
addons:
  sonarcloud:
    organization: "spi1y"
jobs:
  include:
    - stage: lint
      script: make linter || true
    - stage: test & build
      script: make